stages:
  train:
    cmd: python -m project.src.train
    deps:
      - project/src/train.py
      - project/src/data_preprocessing.py
      - project/src/feature_engineering.py
      - data/raw/dataset.csv
    outs:
      - models/best_model.joblib

  evaluate:
    cmd: python -m project.src.evaluate
    deps:
      - project/src/evaluate.py
      - project/src/data_preprocessing.py
      - project/src/feature_engineering.py
      - data/raw/dataset.csv
      - models/best_model.joblib
    metrics:
      - reports/metrics.json